name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2 }} << 'ENDSSH'
          cd networking
          sudo docker-compose down
          sudo docker system prune -af
          git pull
          # Build frontend
          cd frontend
          npm install
          npm run build
          cd ..
          sudo cp -r frontend/dist/* /usr/share/nginx/html/
          sudo systemctl restart nginx
          sudo docker-compose up -d  
          ENDSSH
