name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN  }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and push the Docker images
      run: |
        COMPOSE_VERBOSE=1 docker-compose build
        docker-compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        
    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@35.157.138.185 << 'ENDSSH'
          sudo docker pull estonian/discord-bot:${{ github.sha }}
          sudo docker stop discord-bot || true
          sudo docker rm discord-bot || true
          sudo docker run -d --name discord-bot -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -p 80:80 estonian/discord-bot:${{ github.sha }}
        ENDSSH
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
