name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN  }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and push the Docker images
      run: |
        # export BACKEND_IP=3.74.83.15 
        docker-compose build
        docker-compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY_FRONTEND }}
            
      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.64.52.101 << 'ENDSSH'
            sudo docker pull estonian/social-network-frontend:latest
            sudo docker stop social-network-frontend || true
            sudo docker rm social-network-frontend || true
            sudo docker run -d --name social-network-frontend -p 80:3000 estonian/social-network-frontend:latest
          ENDSSH
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY_BACKEND }}
            
      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.74.83.15 << 'ENDSSH'
            sudo docker pull estonian/social-network-backend:latest
            sudo docker stop social-network-backend || true
            sudo docker rm social-network-backend || true
            sudo docker run -d --name social-network-backend -p 8080:8080 estonian/social-network-backend:latest
          ENDSSH
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
